name: PR Notification

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Show PR info
        run: |
          echo "Pull Request aberto por ${{ github.actor }}"
          echo "Título: ${{ github.event.pull_request.title }}"
          echo "Revisor atribuído: ${{ github.event.pull_request.requested_reviewers }}"
